# .github/workflows/scheduled-builds.yml
name: Trigger cURL on a CRON Schedule

on:
  schedule:
    # Runs "every 10 minute"
    - cron: '0/10 * * * *'
jobs:
  curl_render:
    name: Trigger cURL
    runs-on: ubuntu-latest
    steps:
      - name: cURL request ${{ URL1 }}
        # Hit the onrender endpoint
        run: curl https://${{ URL1 }}/ws
