# .github/workflows/scheduled-builds.yml
name: Trigger cURL on a CRON Schedule

on:
  schedule:
    # Runs "every 10 minute"
    - cron: '0/10 * * * *'
jobs:
  curl_render:
    name: Trigger cURL
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      URL1: ${{ secrets.URL1 }}
    steps:
      - name: cURL request ${{ env.URL1 }}
        # Hit the onrender endpoint
        run: curl https://${{ env.URL1 }}/ws
